---
- name: Build Database Test VM
  hosts: oli-db-test
  become: true
  become_method: sudo

- import_playbook: users.yml
- import_playbook: sqlite.yml
- import_playbook: postgresql.yml
- import_playbook: mongodb.yml
- import_playbook: elasticsearch.yml
- import_playbook: influxdb.yml
# - import_playbook: arrow.yml
